// Account
export const ACCOUNT_FETCH = 'ACCOUNT_FETCH'
export const ACCOUNT_SIGNIN = 'ACCOUNT_SIGNIN'
export const ACCOUNT_SIGNOUT = 'ACCOUNT_SIGNOUT'

// Breadcrumb
export const SET_BREADCRUMB = 'SET_BREADCRUMB'

// Post
export const POST_VOTE = 'POST_VOTE'
export const POST_VOTE_PROCESSING = 'POST_VOTE_PROCESSING'
export const POST_VOTE_RESOLVED = 'POST_VOTE_RESOLVED'
export const POST_VOTE_RESOLVED_ERROR = 'POST_VOTE_RESOLVED_ERROR'

export const POST_RESET_STATE = 'POST_RESET_STATE'
export const POST_LOAD = 'POST_LOAD'
export const POST_LOAD_RESOLVED = 'POST_LOAD_RESOLVED'
export const POST_LOAD_RESPONSES = 'POST_LOAD_RESPONSES'
export const POST_LOAD_RESPONSES_RESOLVED = 'POST_LOAD_RESPONSES_RESOLVED'

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE'
