// Account
export const ACCOUNT_FETCH = 'ACCOUNT_FETCH'
export const ACCOUNT_SIGNIN = 'ACCOUNT_SIGNIN'
export const ACCOUNT_SIGNOUT = 'ACCOUNT_SIGNOUT'
export const ACCOUNT_STATE_RESOLVED = 'ACCOUNT_STATE_RESOLVED'

// Breadcrumb
export const SET_BREADCRUMB = 'SET_BREADCRUMB'

// Forum
export const FORUM_SUBSCRIBE = 'FORUM_SUBSCRIBE'
export const FORUM_UNSUBSCRIBE = 'FORUM_UNSUBSCRIBE'

// Post
export const POST_VOTE = 'POST_VOTE'
export const POST_VOTE_PROCESSING = 'POST_VOTE_PROCESSING'
export const POST_VOTE_RESOLVED = 'POST_VOTE_RESOLVED'
export const POST_VOTE_RESOLVED_ERROR = 'POST_VOTE_RESOLVED_ERROR'
export const POST_VOTE_RESOLVED_ERROR_CLEAR = 'POST_VOTE_RESOLVED_ERROR_CLEAR'

export const POST_SUBMIT_ERROR = 'POST_SUBMIT_ERROR'
export const POST_SUBMIT_RESOLVED = 'POST_SUBMIT_RESOLVED'

export const POST_RESET_STATE = 'POST_RESET_STATE'
export const POST_LOAD = 'POST_LOAD'
export const POST_LOAD_BY_AUTHOR_RESOLVED = 'POST_LOAD_BY_AUTHOR_RESOLVED'
export const POST_LOAD_REPLIES_BY_AUTHOR_RESOLVED = 'POST_LOAD_REPLIES_BY_AUTHOR_RESOLVED'
export const POST_LOAD_REPLIES_BY_AUTHOR_STARTED = 'POST_LOAD_REPLIES_BY_AUTHOR_STARTED'
export const POST_LOAD_RESOLVED = 'POST_LOAD_RESOLVED'
export const POST_LOAD_RESPONSES = 'POST_LOAD_RESPONSES'
export const POST_LOAD_RESPONSES_BY_AUTHOR_RESOLVED = 'POST_LOAD_RESPONSES_BY_AUTHOR_RESOLVED'
export const POST_LOAD_RESPONSES_RESOLVED = 'POST_LOAD_RESPONSES_RESOLVED'

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE'

// search
export const SEARCH = 'SEARCH'
export const SEARCH_RESOLVED = 'SEARCH_RESOLVED'

// state
export const STATE_RESOLVED = 'STATE_RESOLVED'

// status
export const SET_STATUS = 'SET_STATUS'
